on:
  push:
    branches:
      - "exp"
jobs:
  experiment_job:
    runs-on: ubuntu-latest
    name: An experiment job
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.github-action-token }}
    - name: first step
      id: hello
      uses: ./
      with:
        custom-directory: '.md-toc'
    - name: check resulting fs
      run: |
        ls -a
        ls -a ./data
        ls -a ./data/OSCP/
        ls -a ./data/OSCP/Exercises
    - name: Get the output status
      run: echo "The status was ${{ steps.hello.outputs.success }}"