on:
  push:
    branches:
      - "exp"

jobs:
  experiment_job:
    runs-on: ubuntu-latest
    name: An experiment job
    steps:
    - name: checkout
        uses: actions/checkout@v2
    - name: first step
      id: hello
      uses: ./
      with:
        custom-directory: 'md-toc-custom'
    # Use the output from the `hello` step
    - name: Get the output status
      run: echo "The status was ${{ steps.hello.outputs.success }}"